#!/usr/bin/env python3
"""Deterministic, disjoint allocation of source items to (model, mode, variant) groups.

Each domain's full source pool is shuffled once (with a fixed seed) and sliced into
disjoint `samples_per_model`-sized chunks, one per model (in `config["models"]` order) —
no source item is ever generated by more than one model, so the three models' outputs
for a domain always describe three different sets of human source items. Each model's
chunk is then further sliced so every mode gets its configured `count` of items, and
each mode's slice is split into `num_variants` disjoint sub-groups.

The resulting allocation is cached to config/mode_allocations/{domain}__{model}.json on
first use so every team member's run of that domain x model combination sees the
identical item -> (mode, variant) assignment.
"""

import json
import random
from pathlib import Path

import pandas as pd

from filtering import filter_source_items
from wikipedia_quality_filter import filter_by_date, filter_source_data

BASE_DIR = Path(__file__).resolve().parent
ALLOCATIONS_DIR = BASE_DIR / "config" / "mode_allocations"
LOGS_DIR = BASE_DIR / "logs"


def slice_model_items(source_items: list, model_short: str, models: list, samples_per_model: int, seed: int) -> list:
    """Shuffle source_items once (seeded, independent of the global `random` module) and
    return the disjoint `samples_per_model`-sized chunk belonging to `model_short`.

    Every model gets a different contiguous slice of the same shuffle, so slices never
    overlap and the assignment only depends on `models`' order in the config, not on
    which model happens to run first.
    """
    total_needed = samples_per_model * len(models)
    if total_needed > len(source_items):
        raise ValueError(
            f"Need {total_needed} source items ({samples_per_model} x {len(models)} models), "
            f"but only {len(source_items)} source items are available."
        )
    if model_short not in models:
        raise ValueError(f"Unknown model '{model_short}'. Choices: {models}")

    rng = random.Random(seed)
    shuffled = list(source_items)
    rng.shuffle(shuffled)

    start = models.index(model_short) * samples_per_model
    return shuffled[start:start + samples_per_model]


def allocate_modes(model_items: list, mode_config: dict) -> dict:
    """Slice a model's pre-shuffled items into disjoint per-mode, per-variant groups.

    Returns {mode_name: {variant_index: [source_items...]}}.
    """
    total_requested = sum(cfg["count"] for cfg in mode_config.values())
    if total_requested > len(model_items):
        breakdown = ", ".join(f"{mode}={cfg['count']}" for mode, cfg in mode_config.items())
        raise ValueError(
            f"Requested {total_requested} source items across modes ({breakdown}), "
            f"but only {len(model_items)} items were allocated to this model."
        )

    allocation = {}
    cursor = 0
    for mode, cfg in mode_config.items():
        count = cfg["count"]
        num_variants = cfg["num_variants"]
        mode_items = model_items[cursor:cursor + count]
        cursor += count
        allocation[mode] = _split_evenly(mode_items, num_variants)

    return allocation


def _split_evenly(items, num_variants):
    """Split items into num_variants disjoint sub-lists, as evenly as possible, with
    any remainder distributed to the first few variants."""
    n = len(items)
    base, remainder = divmod(n, num_variants)
    groups = {}
    start = 0
    for variant_index in range(num_variants):
        size = base + (1 if variant_index < remainder else 0)
        groups[variant_index] = items[start:start + size]
        start += size
    return groups


def verify_no_overlap(allocation: dict) -> None:
    """Assert no source_id appears in more than one (mode, variant) group."""
    seen = {}  # source_id -> [ "mode/variant_index", ... ]
    for mode, variants in allocation.items():
        for variant_index, items in variants.items():
            group_label = f"{mode}/{variant_index}"
            for item in items:
                source_id = str(item["source_id"])
                seen.setdefault(source_id, []).append(group_label)

    overlaps = {sid: groups for sid, groups in seen.items() if len(groups) > 1}
    if overlaps:
        details = "; ".join(f"{sid} appears in {groups}" for sid, groups in overlaps.items())
        raise AssertionError(f"Overlapping source_id(s) found across allocation groups: {details}")


def _is_present(value):
    if value is None:
        return False
    if isinstance(value, float) and value != value:  # NaN
        return False
    return True


def _trim_item(item, extra_fields):
    trimmed = {"source_id": str(item["source_id"])}
    for field in extra_fields:
        if field in item and _is_present(item[field]):
            trimmed[field] = item[field]
    return trimmed


def get_or_create_allocation(domain: str, model_short: str, config: dict) -> dict:
    """Load the cached allocation for this domain x model if one exists, otherwise
    build it, verify it, save it, and return it. Re-running never re-shuffles or
    produces a different allocation once config/mode_allocations/{domain}__{model}.json
    exists.
    """
    path = ALLOCATIONS_DIR / f"{domain}__{model_short}.json"
    if path.exists():
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    # Deferred import: generate.py imports get_or_create_allocation at module load
    # time, so importing generate.py here eagerly would be circular. By the time this
    # function actually runs, generate.py has finished loading.
    from generate import load_source_data, PLACEHOLDER_KEYS

    domain_cfg = config["domains"][domain]
    seed = config.get("seed", 42)
    models = list(config["models"].keys())

    df = load_source_data(BASE_DIR / domain_cfg["source_file"], domain=domain)

    if domain == "wikipedia":
        # Drop category-only stubs, disambiguation pages, etc. before any shuffling
        # happens — see wikipedia_quality_filter.py for what motivated this and why.
        min_words = domain_cfg.get("min_words", 100)
        clean_df, rejected_df = filter_source_data(df, min_words=min_words)
        LOGS_DIR.mkdir(parents=True, exist_ok=True)
        rejected_df.to_csv(LOGS_DIR / "rejected_sources_wikipedia.csv", index=False, encoding="utf-8-sig")
        print(f"{len(clean_df)} of {len(df)} Wikipedia source rows passed quality filtering.")
        df = clean_df

        # Restrict to articles created AND last-edited before mass LLM-assisted editing
        # became plausible (ChatGPT's launch) — see GPT_ERA_CUTOFF in
        # wikipedia_quality_filter.py. Only applies when source_file has the
        # created_date/last_modified_date columns build_wikipedia_dated_dataset.py adds.
        max_date = domain_cfg.get("max_date")
        if max_date:
            cutoff = pd.Timestamp(max_date, tz="UTC")
            dated_df, dated_rejected_df = filter_by_date(df, cutoff=cutoff)
            dated_rejected_df.to_csv(
                LOGS_DIR / "rejected_sources_wikipedia_date.csv", index=False, encoding="utf-8-sig"
            )
            print(f"{len(dated_df)} of {len(df)} quality-passed rows also created and "
                  f"last-edited before {max_date}.")
            df = dated_df

    source_items = df.to_dict("records")
    source_items = filter_source_items(source_items, domain, min_words=domain_cfg.get("min_words", 0))

    model_items = slice_model_items(source_items, model_short, models, domain_cfg["samples_per_model"], seed)
    allocation = allocate_modes(model_items, domain_cfg["modes"])
    verify_no_overlap(allocation)

    trimmed = {
        mode: {
            str(variant_index): [_trim_item(item, PLACEHOLDER_KEYS) for item in items]
            for variant_index, items in variants.items()
        }
        for mode, variants in allocation.items()
    }

    ALLOCATIONS_DIR.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(trimmed, f, ensure_ascii=False, indent=2)

    return trimmed
